language: node_js
node_js:
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick
script: npm install . && npm test
