language: node_js
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick
script: npm install . && npm test
