language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
  - '3'
  - '2'
  - '0.12'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick
script: npm install . && npm test
