language: node_js
node_js:
  - '4'
  - '3'
  - '2'
  - '0.12'
sudo: true
before_install:
  - 'sudo apt-get install -y build-essential libgraphicsmagick++1-dev libarchive-dev'
script: npm install . && npm test
